version: "3.8"

services:
  #Database that imitates Redshiift
  db:
    image: postgres:15
    container_name: ecom_db
    command: -c listen_addresses='*'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.5.0
    container_name: dbt_worker
    tty: true
    volumes:
      - ./dbt-project:/usr/app/dbt-project
      - ./.dbt/profiles.yml:/root/.dbt/profiles.yml
    environment:
      DBT_USER: ${POSTGRES_USER}
      DBT_PASSWORD: ${POSTGRES_PASSWORD}
    entrypoint: /bin/bash # to prevent turning off immediately

volumes:
  postgres_data:


